test
trackthis/error-reporting pull request #5
Opened 2018-03-06 11:26 UTC by mvallotto

2018-03-06 15:31 UTC, finwo requested changes

2018-03-06 15:31 UTC, finwo commented on package.json
>      "test": "./node_modules/.bin/nyc ./node_modules/.bin/mocha test/* --sort && ./node_modules/.bin/nyc report --reporter=clover"
Why?
It was already there

2018-03-26 08:27 UTC, finwo requested changes

2018-03-26 08:27 UTC, finwo commented on index.js
> +      level = options.defaultLevel;
No `=` alignment

2018-03-26 08:27 UTC, finwo commented on index.js
> +          description: description
No `:` alignment

2018-03-26 08:29 UTC, mvallotto commented on index.js
> +      level = options.defaultLevel;
done

2018-03-26 08:29 UTC, mvallotto commented on index.js
> +          description: description
done

2018-03-26 09:51 UTC, finwo approved these changes

2018-03-26 09:51 UTC, merged